name: CMake

on: push

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Copy sample
      working-directory: ${{github.workspace}}/build
      run: cp ../data/source/chuvas_T_01340039.csv in.csv

    - name: Copy mock data
      working-directory: ${{github.workspace}}/build
      run: cp ../data/fake.csv .

    - name: Run 
      working-directory: ${{github.workspace}}/build
      run: ./clana 


